### ISSUE TITLE
Could not find table 'blazer_connections'

### ISSUE THREAD

**Issue by taiwoayanleye** [ankane/notable#1]
In an attempt to access my admin, I received this error:

"ActiveRecord::StatementInvalid at /
Could not find table 'blazer_connections'"

Here were the codes I used:

gem 'notable'
rails generate notable:requests
rails generate notable:jobs # optional
rake db:migrate

Thanks!

**Comment by ankane** [comment]
Hi @TaiwoAyanleye, what version of Rails are you on?

**Comment by taiwoayanleye** [comment]
Rails 4.1.6
ruby 2.2.0

**Comment by ankane** [comment]
I just pushed an update to Blazer to try to fix this.  Try updating Blazer to see if the error goes away.

``` ruby
gem 'blazer', github: 'ankane/blazer'
```

**Comment by taiwoayanleye** [comment]
Working. Thanks @ankane.
