### ISSUE TITLE
NoMethodError in NotableWeb::HomeController#index

### ISSUE THREAD

**Issue by ACPK** [ankane/notable#11]
When visiting "http://localhost:3000/notable/", I get the following error:

    undefined method `map' for <ActionController::Parameters {} permitted: true>:ActionController::Parameters Did you mean? tap

The error occurs on:
    notable_web (0.0.1) app/controllers/notable_web/home_controller.rb:8:in `index'

**Comment by ankane** [comment]
Hey @ACPK, this was fixed a while ago. Try the latest version.

**Comment by ACPK** [comment]
@ankane  - I believe I'm using the latest release:

    notable (0.2.2)
      request_store
      safely_block (>= 0.1.1)
    notable_web (0.0.1)
      chartkick
      groupdate
      kaminari
      notable
      public_suffix

**Comment by ACPK** [comment]
@ankane - I apologize that I didn't assign this issue to Notable web. The latest release of Notable-Web dates back to December 22, 2014. :)

https://github.com/ankane/notable_web/releases

For organizational reasons,  I'll file a separate issue Notable_web, but I hit the following issue tonight when trying updating "notable_web" from "git://github.com/ankane/notable_web.git"

    ActionController::UnfilteredParameters in NotableWeb::Home#index
    unable to convert unpermitted parameters to hash
    Extracted source (around line #266):


Trace of template inclusion: 
    
    rvm/gems/ruby-2.5.1/bundler/gems/notable_web-af175ea2fe99/app/views/notable_web/home/index.html.erb
