### ISSUE TITLE
undefined method `verified_request?'

### ISSUE THREAD

**Issue by ACPK** [ankane/notable#17]
When using Rails’s `config.api_only = true` feature, you get the error:

    undefined method `verified_request?'

app/controllers/application_controller.rb

    class ApplicationController < ActionController::API
        protect_from_forgery with: :null_session
    end

**Comment by ankane** [comment]
Hey @ACPK, can you paste the full stack trace?

**Comment by ankane** [comment]
Nevermind, found the issue. Should be fixed now.
