### ISSUE TITLE
Consider request belongs_to true_user ?

### ISSUE THREAD

**Issue by bf4** [ankane/notable#18]
Would you be up to a PR to add a 'belongs_to :true_user' to notable requests For when we use an impersonating/masquerading strategy like https://github.com/ankane/pretender ?

(Or alternatively, authenticated_user or virtual_user vs current_user, naming up for grabs)

**Comment by ankane** [comment]
Hey @bf4, thanks for the suggestion. I think it's probably not common enough to include as part of the gem, but you should be able to use `track_request_method` to add it to your application.

**Comment by bf4** [comment]
Ok, so I add a migration to the Notable::Request.table_name and then define something like

```ruby
Notable.track_request_method = lambda do |data, env|
  controller = env["action_controller.instance"] # similar to our Notable.user_method
  data[:true_user] = controller.try(:true_user)
  Notable::Request.create!(data)
end
```

**Comment by ankane** [comment]
Yeah, that's the general idea

**Comment by bf4** [comment]
Ok, closing as resolved then
