### ISSUE TITLE
Consider a request-local and/or model-local 'skip noting model validation errors'

### ISSUE THREAD

**Issue by bf4** [ankane/notable#19]
We have some GET requests which return meta data which check if certain actions on the returned resources are valid. Since these produce active model validation errors, we are getting false positives on these requests.

Rather than dig into the notable internals to disable these, I took a heavier hammer and added to our base controller.

```ruby
  after_action :clear_non_notable_notes, on: [:index, :show]

  def clear_non_notable_notes
    Notable.clear_notes
  end
```

would you accept a PR to conditionally disable the model validations by either/and model-specific flag, request-specific flag?

**Comment by ankane** [comment]
Hey @bf4, thanks for this suggestion as well. This should also be possible with `track_request_method` (the approach in you're currently taking should work fine as well).

**Comment by bf4** [comment]
(With understanding that lib authors shouldn't add features they don't want to use themselves :)

To use `track_request_method` for this purpose would make every notable request bear the brunt of checking if it should create itself after the request has run, which seems worse than having a `Thread.current[:notable_track_validation_errors]= Notable.track_validation_errors = false` then `def track_validation_errors; return unless Notable.track_validation_errors...`

**Comment by bf4** [comment]
Another example is that in our jobs we have some validations which are not notable, like we have 'insert into .. on conflict do update' like pattern on one of our records which sometimes yields an active record uniqueness validation, which we don't care about.  I'd probably just turn off all model validations track in jobs if I had a flag for it. 

I could extend the Notable::ValidationErrors module myself, I suppose

```ruby
require "notable/validation_errors"
module Notable
  class << self
    attr_accessor :track_validation_errors_enabled
  end
  self.track_validation_errors_enabled = true

  def self.track_validation_errors
    key = :notable_track_validation_errors
    if Thread.current.key?(key)
      Thread.current[key]
    else
      track_validation_errors_enabled
    end
  end

  def self.track_validation_errors=(track_validation_errors)
    Thread.current[:notable_track_validation_errors] = track_validation_errors
  end
end

Notable::ValidationErrors.class_eval do
  alias_method :original_track_validation_errors, :track_validation_errors

  def track_validation_errors
    return unless Notable.track_validation_errors
    original_track_validation_errors
  end
end
```

**Comment by ankane** [comment]
`track_request_method`/`track_job_method` works for that situation as well, so I don't think extra complexity is needed. That being said, it's open source, so you can fork and adapt it to your application.

**Comment by bf4** [comment]
I'd much rather extend the gem than fork it.  Would you be open to having an escape valve on the active record instance? like a method 'skip_track_validation_errors'? I doubt the cost of method dispatch is too high.

```diff
  def track_validation_errors
+    return if skip_track_validation_errors
    if errors.any?
      Notable.track "Validation Errors", "#{self.class.name}: #{errors.full_messages.join(", ")}"
    end
  end

+  def skip_track_validation_errors # or an attr_accessor. ¯\_(ツ)_/¯
+    false
+  end
```

**Comment by bf4** [comment]
Closing as resolved by discussion
