### ISSUE TITLE
Default logging not working

### ISSUE THREAD

**Issue by kshahkshah** [ankane/notable#2]
Rails 4.2.4, Ruby 2.2.3, running on my production instance of Ubuntu 14.04 at Digital Ocean.

Latest gem version of notable, no settings specified, mounting notable-web at as shown with devise (checks user#admin? == true)

Nothing.. no logging..

Purposefully hitting 404s, etc. 

`Notable.enabled == true` when asked in the console

**Comment by kshahkshah** [comment]
Sorry for the super vague report, I have no place to start, but I'll dive into the code shortly otherwise and find one.

**Comment by ankane** [comment]
Cleaning up issues
