### ISSUE TITLE
Feature: Ability to disable features

### ISSUE THREAD

**Issue by ACPK** [ankane/notable#4]
In the Gem todo list, was it referring to the website's features if they're using Rollbar or the gem's feature? I'm thinking about how to disable a site's feature (ex: one of the payment options) if it's causing errors due to a third party api.

**Comment by ankane** [comment]
Hey Andrew, it refers to disabling specific features of Notable, in case you only want to track specific events.

**Comment by ACPK** [comment]
@ankane I know it's been 9 years but was a feature added to be able to disable specific events (i.e. tracking 404s)?
