### ISSUE TITLE
Switch to ActiveJob instead of individual gem integrations

### ISSUE THREAD

**Issue by ankane** [ankane/notable#7]

**Comment by ankane** [comment]
Done

**Comment by vicramon** [comment]
Oh hello @ankane . It would be nice if notable jobs supported sidekiq alone without ActiveJob being required.

https://github.com/mperham/sidekiq/wiki/Active+Job#performance

I know, PRs welcome, I'm just a busy guy

**Comment by ankane** [comment]
Don't think I'd accept a PR for this one, as you can already use Sidekiq with ActiveJob, and the performance increase isn't worth the maintenance effort. Your best bet is to override the `track` methods to do this for your app.
